# Generated by Django 4.1.4 on 2023-08-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiserv_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiservpaymentmethod',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='fiservpaymentmethod',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='Shared Secret'),
        ),
    ]
