# Generated by Django 4.1.4 on 2023-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tncs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnc',
            name='country',
            field=models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile'), ('br', 'Brasil')], db_index=True, max_length=2, verbose_name='país'),
        ),
    ]
