# Generated by Django 4.1.4 on 2023-05-29 22:58

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='identificador')),
                ('country', models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile')], db_index=True, max_length=2, verbose_name='país')),
                ('display_name', models.CharField(blank=True, help_text='How the payment method will be displayed on the frontend. If empty, identifier will be used instead', max_length=255, verbose_name='Display name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('content_type', models.ForeignKey(on_delete=models.SET(payments.models.get_default_payment_method_content_type), related_name='payment_methods', to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'abstract': False,
            },
        ),
    ]
