# Generated by Django 4.1.4 on 2023-05-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(blank=True, help_text='How the payment method will be displayed on the frontend. If empty, identifier will be used instead', max_length=255, verbose_name='Nombre para mostrar'),
        ),
    ]
