# Generated by Django 4.1.4 on 2023-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_homepage_about_us_module_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='country',
            field=models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile'), ('br', 'Brasil')], db_index=True, max_length=2, unique=True, verbose_name='país'),
        ),
    ]
