# Generated by Django 4.1.4 on 2023-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_cbu',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='cbu'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_cuit',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='cuit'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_number',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_type',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='tipo de cuenta'),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_condition',
            field=models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributo', 'Monotributo'), ('consumidor_final', 'Consumidor Final'), ('exento', 'Exento')], default='consumidor_final', max_length=50, null=True, verbose_name='condicion IVA'),
        ),
    ]
