# Generated by Django 4.1.4 on 2023-05-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bank_cbu_user_bank_cuit_user_bank_name_and_more'),
        ('users', '0002_user_billing_address_user_shipping_address'),
    ]

    operations = [
    ]
