# Generated by Django 4.1.4 on 2023-06-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20230517_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=True, verbose_name='vendedor'),
        ),
    ]
