# Generated by Django 4.1.4 on 2023-03-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('title', models.CharField(max_length=150, verbose_name='fila')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio_final')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('ready_to_go', models.BooleanField(verbose_name='ready_to_go')),
                ('add_info', models.TextField(verbose_name='add_info')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='events.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'entradas a la venta',
                'verbose_name_plural': 'entradas a la venta',
                'ordering': ('event', 'price'),
            },
        ),
        migrations.CreateModel(
            name='EventPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('title', models.CharField(max_length=150, verbose_name='nombre')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_places', to='events.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'sectores del evento',
                'verbose_name_plural': 'sectores del evento',
                'ordering': ('event', 'title'),
            },
        ),
    ]
