# Generated by Django 4.1.4 on 2023-03-08 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtickets_eventplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtickets',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_seller', to='events.category', verbose_name='vendedor'),
            preserve_default=False,
        ),
    ]
