# Generated by Django 4.1.4 on 2023-03-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtickets_eventplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtickets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_seller', to='events.category', verbose_name='vendedor'),
        ),
    ]
