# Generated by Django 4.1.4 on 2023-03-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventtickets_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPlaces',
            new_name='EventPlace',
        ),
        migrations.RenameModel(
            old_name='EventTickets',
            new_name='EventTicket',
        ),
    ]
