# Generated by Django 4.1.4 on 2023-03-02 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_eventtickets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtickets',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_place', to='events.eventplaces', verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='eventtickets',
            name='quantity',
            field=models.TextField(default=0, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='eventtickets',
            name='ticket_type',
            field=models.CharField(choices=[('Entradas de papel', 'Entradas de papel'), ('Transferencia de entradas electrónicas', 'Transferencia de entradas electrónicas'), ('E-ticket', 'E-ticket')], default='Entradas de papel', max_length=50),
        ),
        migrations.AddField(
            model_name='eventtickets',
            name='together',
            field=models.IntegerField(choices=[(0, 'Sin preferencia'), (1, 'Se venden juntas'), (2, 'No dejar 1 sin vender'), (3, 'De a pares')], default=0),
        ),
        migrations.AlterField(
            model_name='eventtickets',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio final'),
        ),
        migrations.AlterField(
            model_name='eventtickets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_seller', to=settings.AUTH_USER_MODEL, verbose_name='vendedor'),
        ),
    ]
