# Generated by Django 4.1.4 on 2023-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_section_ticket_remove_eventticket_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.CharField(default='', max_length=50, verbose_name='fila'),
        ),
    ]
