# Generated by Django 4.1.4 on 2023-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
