# Generated by Django 4.1.4 on 2023-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_ticket_attachment_alter_ticket_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
