# Generated by Django 4.1.4 on 2023-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='country',
            field=models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile'), ('br', 'Brasil')], db_index=True, max_length=2, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile'), ('br', 'Brasil')], db_index=True, max_length=2, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='country',
            field=models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile'), ('br', 'Brasil')], db_index=True, max_length=2, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(choices=[('ar', 'Argentina'), ('cl', 'Chile'), ('br', 'Brasil')], db_index=True, max_length=2, verbose_name='país'),
        ),
    ]
