# Generated by Django 4.1.4 on 2023-06-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='individual_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='coeficiente de venta especial'),
        ),
        migrations.AddField(
            model_name='event',
            name='pay_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='dia de liquidacion'),
        ),
    ]
