# Generated by Django 4.1.4 on 2023-06-27 18:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_individual_percentage_event_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sub_section',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
