# Generated by Django 4.1.4 on 2023-06-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_section_subsection_ticket_subsection'),
        ('events', '0019_section_sub_section'),
    ]

    operations = [
    ]
