# Generated by Django 4.1.4 on 2023-07-07 18:52

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_merge_20230627_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ready_date',
            field=models.DateField(blank=True, null=True, verbose_name='dia de disponibilidad'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_section',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(verbose_name='sub-sector'), blank=True, null=True, size=None),
        ),
    ]
