# Generated by Django 4.1.4 on 2023-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_ticket_ready_date_alter_section_sub_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subsection',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='subsector'),
        ),
    ]
