# Generated by Django 4.1.4 on 2023-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_ticket_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='fila'),
        ),
    ]
