# Generated by Django 4.1.4 on 2023-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_ticket_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_main_images', verbose_name='imagen header'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_main_images', verbose_name='imagen principal'),
        ),
        migrations.AddField(
            model_name='venue',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_main_images', verbose_name='imagen header'),
        ),
        migrations.AddField(
            model_name='venue',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_main_images', verbose_name='imagen principal'),
        ),
    ]
