# Generated by Django 4.1.4 on 2023-07-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_organizer_header_image_organizer_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen header'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen principal'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen header'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen principal'),
        ),
    ]
