# Generated by Django 4.1.4 on 2023-10-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_ticket_events_tick_seller__b674e2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='allow_row',
            field=models.BooleanField(default=True, verbose_name='admite fila?'),
        ),
    ]
