# Generated by Django 4.1.4 on 2022-12-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ('country',), 'verbose_name': 'página principal', 'verbose_name_plural': 'páginas principales'},
        ),
    ]
