# Generated by Django 4.1.4 on 2023-08-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viumi_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viumipaymentmethod',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='viumipaymentmethod',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='ID Cliente'),
        ),
    ]
