# Generated by Django 4.1.4 on 2023-05-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_alter_paymentmethod_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoPaymentMethod',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.paymentmethod')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access token')),
                ('public_key', models.CharField(max_length=255, verbose_name='Public key')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'abstract': False,
            },
            bases=('payments.paymentmethod',),
        ),
    ]
