# Generated by Django 4.1.4 on 2023-09-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
        ('mercadopago_payments', '0002_alter_mercadopagopaymentmethod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('request_data', models.JSONField(verbose_name='data (request)')),
                ('response_data', models.JSONField(verbose_name='data (response)')),
                ('checkout_id', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='checkout ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MercadoPago_payments', to='orders.order', verbose_name='compra')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MercadoPago_payments', to='mercadopago_payments.mercadopagopaymentmethod', verbose_name='medio de pago')),
            ],
            options={
                'verbose_name': 'Pago MercadoPago',
                'verbose_name_plural': 'Pagos MercadoPago',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoIPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('data', models.JSONField(verbose_name='data (request)')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipns', to='mercadopago_payments.mercadopagopayment', verbose_name='Pago MercadoPago')),
            ],
            options={
                'verbose_name': 'IPN MercadoPago',
                'verbose_name_plural': 'IPNs MercadoPago',
                'ordering': ('-created',),
            },
        ),
    ]
