# Generated by Django 4.1.4 on 2023-06-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20230606_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Liquidacion vendedor',
                'verbose_name_plural': 'Liquidaciones vendedor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderticket',),
        ),
    ]
